name: 'Bash 4.0'
description: 'Run a command using Bash version 4.0'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.command }}
    - ${{ inputs.failOnError }}
inputs:
  command:
    description: 'Bash command or path to executable or script to run'
    required: true
  failOnError:
    description: 'When set to true (default), the action will return an error if the command returns a non-zero exit code'
    require: true
    default: true
outputs:
  stdout:
    description: 'The standard output (STDOUT) of the executed command'
  stderr:
    description: 'The standard error (STDERR) of the executed command'
  output:
    description: 'The combines standard output and error of the executed command'
  exitcode:
    description: 'The numeric exit code of the executed command (0 indicates success)'
  passed:
    description: 'If the executed command exited with 0 exit code, this value will equal "true", otherwise it will equal "false"'
  failed:
    description: 'If the executed command exited with 0 exit code, this value will equal "false", otherwise it will equal "true"'
